apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-database-configmap
data:
  POSTGRES_DB: shop

---

apiVersion: v1
kind: Secret
metadata:
  name: shop-database-secret
data:
  POSTGRES_PASSWORD: shop

---

apiVersion: v1
kind: Service
metadata:
  name: shop-database-service
spec:
  selector:
    app: shop-database
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shop-database
spec:
  selector:
    matchLabels:
      app: shop-database-label
  serviceName: <ServiceName>
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


