apiVersion: apps/v1 ## just v1 give error
kind: Deployment ## Deployement vs Pods
metadata:
  name: shop-backend
spec:
  selector:
    matchLabels:
      app: shop-backend-label 
  replicas: 3
  template:
    metadata:
      labels:
        app: shop-backend-label
    spec:
      containers:
        - name: shop-backend
          image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:no-database
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
