apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
spec:
  selector:
    app: shop-backend-label
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: shop-frontend-service
spec:
  selector:
    app: shop-frontend-label
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  labels:
    name: shop-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - student-45.devshop.codelab.dwidwi.tech
      secretName: tls-secret
  rules:
    - host: student-45.devshop.codelab.dwidwi.tech
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: shop-frontend-service
              port: 
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: shop-backend-service
              port: 
                number: 8080


